[package]
name = "http-flood-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = [ "macros", "rt-multi-thread", "io-util", "net", "time", "sync" ] }
byte-unit = "4"
rand = { version = "0.8", features = [ "small_rng" ] }
