[package]
name = "http-flood-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = [ "macros", "rt-multi-thread", "io-util", "net", "time", "sync" ] }
once_cell = "1.9"
byte-unit = "4"
